---
  - name: Assure java path
    file:
      state: directory
      path: /opt/java
      owner: root
      group: wheel
  - name: Assure jdk8 path
    file:
      state: directory
      path: /opt/java/jdk8
  - name: Install java
    unarchive:
      src: jdk-8u101-linux-x64.tar.gz
      dest: /opt/java/jdk8
      owner: root
      group: wheel
  - name: Link to java
    file:
      state: link
      src: /opt/java/jdk8/jdk1.8.0_101/bin/java
      dest: /usr/bin/java
      force: yes