---
  - name: Install mule app
    unarchive:
      src: "mule-ee-distribution-standalone-{{ muleBaseVersion }}.tar.gz"
      dest: /opt
      owner: "{{ muleUser }}"
      group: "{{ muleGroup }}"
  - name: Link mule
    file:
      state: link
      src: "/opt/mule-enterprise-standalone-{{ muleBaseVersion }}"
      dest: /opt/mule-esb
      force: yes